### ISSUE TITLE
Does it compile with rust 1.0?

### ISSUE THREAD

**Issue by wpoosanguansit** [michaelwoerister/rs-persistent-datastructures#2]
I do have hamt.rs:1334:5: 1334:9 error: `priv` is a reserved keyword.  Is there some other steps to follow to compile the code?  Thanks for your help.

**Comment by nikomatsakis** [comment]
I just built the most recent of the code with Rust 1.7.0, so I'm guessing this issue can be closed. :)

**Comment by michaelwoerister** [comment]
Yes, I updated it some time ago and it seems to build fine since then.
