### ISSUE TITLE
Is this crate still activily maintained?

### ISSUE THREAD

**Issue by dpc** [michaelwoerister/rs-persistent-datastructures#6]
Seems there has been PR to fix it etc.

If not, I think I could at lest take it over, integratye PRs to fix it and publish on crates.io so it's usable.

**Comment by dpc** [comment]
@lise-henry @teh - Are any of you interesting in maintaining it?

**Comment by lise-henry** [comment]
oh no, I just looked at this library and tried to fix the errors that rustc gave me to get it to compile, but I have no competence to go far beyond that ^^

**Comment by dpc** [comment]
You will learn along the way. :) . Right now having this updated, compiling and published on crates.io would be a big step up.

**Comment by nikomatsakis** [comment]
Seems like it's building now? I just built with Rust 1.7.0.
