### ISSUE TITLE
Question about memory management

### ISSUE THREAD

**Issue by flo-l** [michaelwoerister/rs-persistent-datastructures#9]
Out of curiosity: I've skimmed your code and as far as I understand you're using refcounts for memory management (Please correct me if I'm wrong). Doesn't that change the algorithmic complexity from O(log n) to O(n), because you need to visit all nodes after every iteration to update the refcount?

I'm asking because I'm currently looking into persistent datastructures, especially how to implement them in Rust. Your solution is a great source of info. I like how your code can mutate the structure if it's safe to do so, that's a very nice optimization!

**Comment by michaelwoerister** [comment]
It's been a while that I took a look at the code but as far as I can tell, the complexity should still be O(log n). An insertion of deletion should just modify ref-counts of nodes along the path down tree, which is (log n).

**Comment by flo-l** [comment]
Thank you for your reply!

Please correct me if I'm wrong, but I think that if you create a new tree, which shares nodes with other trees, you'd have to increment all refcounts of these shared nodes. Isn't this O(n)?

**Comment by michaelwoerister** [comment]
> Isn't this O(n)?

No, since you only increment the ref-counts of directly referenced nodes, not all the ref-counts of the sub-trees behind those.

**Comment by flo-l** [comment]
Oh I see, of course you're right! Thank you for clarifying this!!
